### ISSUE TITLE
Using `dev-master` is bad practice.

### ISSUE THREAD

**Issue by clemblanco** [Codeko/magento2-disable-newsletter#2]
https://lornajane.net/posts/2015/relying-on-a-dev-master-dependency-in-composer

**Comment by clemblanco** [comment]
Especially considering you're already using version `1.0.0` in your `/etc/module.xml`.
Why not re-using the same version and make a release with a proper tag?

**Comment by jg-development** [comment]
+1 plz provide a 1.0.0 tag ...
thx in advance

**Comment by boris-burgos** [comment]
Created a v1.0.3 version and tag.
