### ISSUE TITLE
Remove the PHP dependency

### ISSUE THREAD

**Issue by aKalisch** [Codeko/magento2-disable-newsletter#3]
Since Magento 2.3.3 is out PHP 7.3 support is enabled.
Having the php dependency inside the composer.json is bad due to fast progress in the php versions.
Just make sure your code is fine with the latest version of Magento 2.

Magento 2.3.x doesn't support PHP 7.0 and below it's fine to remove it.

**Comment by boris-burgos** [comment]
PRs are welcome @aKalisch :-)
